### ISSUE TITLE
Cannot get timecourses for legendre polynomial basis function

### ISSUE THREAD

**Issue by mccoyb4** [VU-Cog-Sci/response_fytter#2]
Hi Gilles,

The response_fytter.get_timecourses() function gives a value shape error when using the legendre polynomials basis set. I'm attaching a document with the code I've used for setting it up and the traceback of the error. 

The shape implies that there might be doubling up of oversampling (using the default oversample_design_matrix=20). At the end of the doc there's adapted code where I've removed that and it seems to work. 

A related minor issue is that it seems that the confounds need to be removed again after the regression for the response_fytter.get_timecourses() function to work.

Cheers,
Bronagh

[response_fytter_legendre_issue.pdf](https://github.com/VU-Cog-Sci/response_fytter/files/2159275/response_fytter_legendre_issue.pdf)

**Comment by Gilles86** [comment]
Fixed in this commit
https://github.com/VU-Cog-Sci/response_fytter/commit/f53a85f4a380f532e8cf98ad7144e48acfdce178

close

**Comment by Gilles86** [comment]
@tknapen, can you close this issue and maybe also make me admin of this repository?
