### ISSUE TITLE
No getting rsq values for concatenated response fitters

### ISSUE THREAD

**Issue by tknapen** [VU-Cog-Sci/response_fytter#20]
concatenated response fitters don't allow the getting of rsq values, bc get_rsq function doesn't keep track of whether a concatenatedresponsefitter or a normal responsefitter did the actual fitting... Will look at this more together with @gjheij.

**Comment by Gilles86** [comment]
Fixed in this commit:
https://github.com/VU-Cog-Sci/nideconv/commit/aa9b30fb39e1bb103b9cd2a607d00f7c8f3e1f8d
