### ISSUE TITLE
Extracting parameter estimates

### ISSUE THREAD

**Issue by leotozzi88** [VU-Cog-Sci/response_fytter#32]
Dear Experts, 

After fitting the model with g_model.fit(), how can a user extract the parameter estimates? 

For example, when I fit a canonical HRF I would like to extract the parameter estimate by which this canonical HRF is weighted for each condition. 

Similarly, if I fit a Fourier series with 9 waves, I would expect 9 parameters per condition per individual. 

The reason I want to do this is that I am trying to get to a measure of response for each condition and individual. One way of doing this would be to calculate the integral for the timeseries of each condition for each individual. But I would also like to try the more common approach used in neuroimaging of extracting parameter estimates. 

Thank you very much!

**Comment by gjheij** [comment]
Hi,

These are stored in the `betas` attribute of `ResponseFitter`. Combined with the design matrix, you can generate predictions for individual basis sets, rather than a full model including all of them.

Best,
Jurjen
