### ISSUE TITLE
Installation error due to deprecated sklearn

### ISSUE THREAD

**Issue by jvschw** [VU-Cog-Sci/response_fytter#35]
Dear developers (hi Tomas)
my installation on a Mac M3
Python 3.9.19 (main, Mar 21 2024, 12:07:41) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin

conda create --name nideconv
conda activate nideconv
conda install numpy scikit-learn pystan
pip install git+https://github.com/VU-Cog-Sci/nideconv

fails with the following messages:

pip install git+https://github.com/VU-Cog-Sci/nideconv
Collecting git+https://github.com/VU-Cog-Sci/nideconv
  Cloning https://github.com/VU-Cog-Sci/nideconv to /private/var/folders/k8/w6f23_rx489b8ttd_trmscwc0000gn/T/pip-req-build-99el_gp1
  Running command git clone --filter=blob:none --quiet https://github.com/VU-Cog-Sci/nideconv /private/var/folders/k8/w6f23_rx489b8ttd_trmscwc0000gn/T/pip-req-build-99el_gp1
  Resolved https://github.com/VU-Cog-Sci/nideconv to commit bdee405c671329c79bf200d26f087aea62557106
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cython in ./anaconda3/envs/nideconv/lib/python3.9/site-packages (from nideconv==0.1rc6) (3.0.10)
Requirement already satisfied: numpy in ./anaconda3/envs/nideconv/lib/python3.9/site-packages (from nideconv==0.1rc6) (1.26.4)
Requirement already satisfied: scipy in ./anaconda3/envs/nideconv/lib/python3.9/site-packages (from nideconv==0.1rc6) (1.12.0)
Collecting sklearn (from nideconv==0.1rc6)
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I also tried with setting the environment variable
 SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True

but got the same results.

Can you help?

Best,
Jens

**Comment by gjheij** [comment]
Hi Jens, 

This is indeed a deprecated name for `sklearn`. It needs to be `scikit-learn`, instead. My advice: `git clone` the repository somewhere and adjust the name in the `requirements.txt`-file until the pull request has been approved.

Best,
Jurjen

**Comment by gjheij** [comment]
Should be ok now.
