### ISSUE TITLE
Name for Python package

### ISSUE THREAD

**Issue by Gilles86** [VU-Cog-Sci/response_fytter#5]
We need to have a catchy name for this package.

Current candidates:
 * response_fytter
 * ezdeconv
 * phlogiston
 * pynnacle
 * decopy
 * deconpy
 * deconvpy
 * PyTimecourse
 * FitimePy

@mszinte , @tknapen , @daanvanes @mccoy4b: any thoughts?

**Comment by Gilles86** [comment]
Some thoughts:

 * I just don't like the name response_fytter
 * ez-deconv seems too easy
 * phlogiston is fun, but I can't really pitch why this is a good name
 * FitimePy and Pytimecourse, note there is already [nitime](http://nipy.org/nitime/index.html)
 * Maybe deconvpy is best I heard so far.

**Comment by eort** [comment]
Of all the ones above, decoPy sounds best to me. 

If there wasn't already [PyFit](https://wiki.python.org/moin/PyFit), I'd suggest pyFyt. Maybe ezFyt?

**Comment by Gilles86** [comment]
OK. It's gonna be 'nideconv'. 
This name:

- Makes (for some people) immediately clear what this package is about
- Can fit in the whole neuroimagign ecosystem of nipype, nitime, nighres, nilearn, etc.
- Is kinda nice.
